// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLQ3TxK3IV8-9cwXXtG-xKQF0fx0wbLGI',
    appId: '1:665687624015:web:ffdbe7ccd1a14a471bdd3a',
    messagingSenderId: '665687624015',
    projectId: 'todo-list-app-291a2',
    authDomain: 'todo-list-app-291a2.firebaseapp.com',
    storageBucket: 'todo-list-app-291a2.firebasestorage.app',
    measurementId: 'G-LFYJ1H3R0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0-0QXXbttnBQp2KNtjdZQjw4a_MH7DIM',
    appId: '1:665687624015:android:4017feb90a1c6f6f1bdd3a',
    messagingSenderId: '665687624015',
    projectId: 'todo-list-app-291a2',
    storageBucket: 'todo-list-app-291a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPTGlmKhCNglSafVp1ctE6R2wxeY49S0w',
    appId: '1:665687624015:ios:3531b964399cf31e1bdd3a',
    messagingSenderId: '665687624015',
    projectId: 'todo-list-app-291a2',
    storageBucket: 'todo-list-app-291a2.firebasestorage.app',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPTGlmKhCNglSafVp1ctE6R2wxeY49S0w',
    appId: '1:665687624015:ios:3531b964399cf31e1bdd3a',
    messagingSenderId: '665687624015',
    projectId: 'todo-list-app-291a2',
    storageBucket: 'todo-list-app-291a2.firebasestorage.app',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLQ3TxK3IV8-9cwXXtG-xKQF0fx0wbLGI',
    appId: '1:665687624015:web:b5fdbba2c9abb29d1bdd3a',
    messagingSenderId: '665687624015',
    projectId: 'todo-list-app-291a2',
    authDomain: 'todo-list-app-291a2.firebaseapp.com',
    storageBucket: 'todo-list-app-291a2.firebasestorage.app',
    measurementId: 'G-V2C3RZ678Q',
  );

}